Indent the functions in "run_micro"

diff --git a/run_micro b/run_micro
--- a/run_micro
+++ b/run_micro
@@ -2,69 +2,69 @@
 
 # Functions
 checkCommand() {
-# Check, if the command exists on the machine
-# args: command(str)
-local commandarg=$1
-if ! [ -x "$(command -v "$commandarg")" ]; then
-	echo "Command $commandarg not found." >&2
-	exit 1
-fi
-return 0
+	# Check, if the command exists on the machine
+	# args: command(str)
+	local commandarg=$1
+	if ! [ -x "$(command -v "$commandarg")" ]; then
+		echo "Command $commandarg not found." >&2
+		exit 1
+	fi
+	return 0
 }
 checkHash() {
-# Check, if the given hash is correct
-# args: completePathToFile(str), sha256Hash(str)
-local file=$1;
-local file_checksum=$2;
+	# Check, if the given hash is correct
+	# args: completePathToFile(str), sha256Hash(str)
+	local file=$1;
+	local file_checksum=$2;
 
-sha_output=$(sha256sum "$file" | cut -d " " -f 1)
+	sha_output=$(sha256sum "$file" | cut -d " " -f 1)
 
-if ! [ "$file_checksum" = "$sha_output" ]; then
-	return 1
-fi
-return 0
-}
-checkFile() {
-# Check, if the file exists
-# args: completePathToFile(str)
-local file=$1
-if ! [ -e "$file" ]; then
-	return 1
-fi
-return 0
-}
-checkDependency() {
-# Download the file, if not exists in the machine.
-# args: completePathToFile(str), downloadURL(str)
-local file_name=$1
-local downloadURL=$2
-if ! checkFile "$file_name"; then
-	wget "$downloadURL" -O "$file_name"
-
-	if ! checkFile "$file_name"; then
-
+	if ! [ "$file_checksum" = "$sha_output" ]; then
 		return 1
 	fi
-fi
-return 0
+	return 0
+}
+checkFile() {
+	# Check, if the file exists
+	# args: completePathToFile(str)
+	local file=$1
+	if ! [ -e "$file" ]; then
+		return 1
+	fi
+	return 0
+}
+checkDependency() {
+	# Download the file, if not exists in the machine.
+	# args: completePathToFile(str), downloadURL(str)
+	local file_name=$1
+	local downloadURL=$2
+	if ! checkFile "$file_name"; then
+		wget "$downloadURL" -O "$file_name"
+
+		if ! checkFile "$file_name"; then
+
+			return 1
+		fi
+	fi
+	return 0
 }
 inspectFile() {
-# Check the file with the given hash
-# args: completePathToFile(str), downloadURL(str), Sha256Hash(str)
-local file=$1
-local downloadURL=$2
-local fileHash=$3
+	# Check the file with the given hash
+	# args: completePathToFile(str), downloadURL(str), Sha256Hash(str)
+	local file=$1
+	local downloadURL=$2
+	local fileHash=$3
 
-if ! checkDependency "$file" "$downloadURL"; then
-		echo "File($(basename "$file_name")) could not be downloaded." >&2
-	exit 1
-fi
+	if ! checkDependency "$file" "$downloadURL"; then
+			echo "File($(basename "$file_name")) could not be downloaded." >&2
+		exit 1
+	fi
 
-if ! checkHash "$file" "$fileHash"; then
-	echo "Invalid checksum for $(basename "$file")" >&2
-	exit 1
-fi
-return 0
+	if ! checkHash "$file" "$fileHash"; then
+		echo "Invalid checksum for $(basename "$file")" >&2
+		exit 1
+	fi
+	return 0
 }
 
 
