May the Bash with you
- Add a checksum for the files
- Check, if the commands are available
- Do not download the files again, if already downloaded

diff --git a/run_micro b/run_micro
--- a/run_micro
+++ b/run_micro
@@ -1,43 +1,107 @@
 #!/bin/bash
 
+# Functions
+checkCommand() {
+# Check, if the command exists on the machine
+# args: command(str)
+local commandarg=$1
+if ! [ -x "$(command -v "$commandarg")" ]; then
+	echo "Command $commandarg not found." >&2
+	exit 1
+fi
+return 0
+}
+checkHash() {
+# Check, if the given hash is correct
+# args: completePathToFile(str), sha256Hash(str)
+local file=$1;
+local file_checksum=$2;
+
+sha_output=$(sha256sum "$file" | cut -d " " -f 1)
+
+if ! [ "$file_checksum" = "$sha_output" ]; then
+	return 1
+fi
+return 0
+}
+checkFile() {
+# Check, if the file exists
+# args: completePathToFile(str)
+local file=$1
+if ! [ -e "$file" ]; then
+	return 1
+fi
+return 0
+}
+checkDependency() {
+# Download the file, if not exists in the machine.
+# args: completePathToFile(str), downloadURL(str)
+local file_name=$1
+local downloadURL=$2
+if ! checkFile "$file_name"; then
+	wget "$downloadURL" -O "$file_name"
+
+	if ! checkFile "$file_name"; then
+
+		return 1
+	fi
+fi
+return 0
+}
+inspectFile() {
+# Check the file with the given hash
+# args: completePathToFile(str), downloadURL(str), Sha256Hash(str)
+local file=$1
+local downloadURL=$2
+local fileHash=$3
+
+if ! checkDependency "$file" "$downloadURL"; then
+		echo "File($(basename "$file_name")) could not be downloaded." >&2
+	exit 1
+fi
+
+if ! checkHash "$file" "$fileHash"; then
+	echo "Invalid checksum for $(basename "$file")" >&2
+	exit 1
+fi
+return 0
+}
+
+
+# Check, if the commands are available
+commands=("wget" "sha256sum")
+for command in "${commands[@]}"; do
+	checkCommand "$command"
+done
+
 HTEMP="/tmp/holarseweb"
 mkdir -p $HTEMP
 
-# Lädt Payara Micro nach $HTEMP herunter, falls noch nicht vorhanden. Dann wird Holarse-Web deployt und gestartet.
+# Payara
 PAYARA_MICRO_JAR="payara-micro-4.1.2.181.jar"
-PAYARA_DOWNLOAD_URL="https://info.payara.fish/cs/c/?cta_guid=21e00628-5d9e-400a-9805-1fc99fe0de87&placement_guid=0c1037e0-adaf-4401-b888-05088602db6a&portal_id=334594&redirect_url=APefjpHk5ZarY-jyJWeewr-aC04o2DTfTQ4Jw5fabqj82x-oQGcdEwnsw1EekoREwdGUiHhxlkGSUhPe5LTZxfcSaK_os90hKrGMkdw_hnWxg6Y7IyCoZn8&hsutk=c7a0000014e21dc71b2a0161ffe028ad&canon=https%3A%2F%2Fwww.payara.fish%2Fdownloads&click=6a538736-87a1-4b82-8e81-4e37f3f832ae&utm_referrer=https%3A%2F%2Fwww.payara.fish%2F"
+PAYARA_SHA256="ba2abcbfa49a56308470a55463472da5b5507c5de756ac53cca8925e799bbee7"
+PAYARA_DOWNLOAD_URL="https://s3-eu-west-1.amazonaws.com/payara.fish/Payara+Downloads/Payara+4.1.2.181/$PAYARA_MICRO_JAR"
+inspectFile "$HTEMP/$PAYARA_MICRO_JAR" $PAYARA_DOWNLOAD_URL $PAYARA_SHA256
 
+# Postgresql JDBC
 POSTGRESQL_JDBC_JAR="postgresql-42.2.1.jar"
-POSTGRESQL_JDBC_URL="https://jdbc.postgresql.org/download/$POSTGRESQL_JDBC_JAR"
+POSTGRESQL_JDBC_SHA256="d800ad754c7265b3bc06425d3ea0059a2a3226527226cecfd459f74b0be7d6ed"
+POSTGRESQL_JDBC_DOWNLOAD_URL="https://jdbc.postgresql.org/download/$POSTGRESQL_JDBC_JAR"
+inspectFile "$HTEMP/$POSTGRESQL_JDBC_JAR" $POSTGRESQL_JDBC_DOWNLOAD_URL $POSTGRESQL_JDBC_SHA256
+
 
 PAYARA_OPTS="--disablephonehome --nocluster"
 HOLARSE_WAR="target/HolarseWeb-1.0-SNAPSHOT.war"
-
-# payara herunterladen falls nötig
-echo "make sure application server is available..."
-if [[ ! -e "$HTEMP/$PAYARA_MICRO_JAR" ]]; then
-    wget "$PAYARA_DOWNLOAD_URL" -O "$HTEMP/$PAYARA_MICRO_JAR"
+# Compile Holarse-Web, if it is missing
+if ! checkFile "$HOLARSE_WAR"; then
+	echo "Holarse-Web will be compiled"
+#	mvn clean package
 fi
 
-# postgresql jdbc-treiber herunterladen falls nötig
-if [[ ! -e "$HTEMP/$POSTGRESQL_JDBC_JAR" ]]; then
-    wget "$POSTGRESQL_JDBC_URL" -O "$HTEMP/$POSTGRESQL_JDBC_JAR"
-fi
-
-# holarse bauen falls nötig
-echo "make sure holarse-web is built..."
-if [[ ! -e "$HOLARSE_WAR" ]]; then
-    mvn clean package
-fi
-
+# Print variables
 echo "PAYARA_MICRO_JAR: $PAYARA_MICRO_JAR"
 echo "PAYARA_OPTS     : $PAYARA_OPTS"
 echo "HOLARE_WAR      : $HOLARSE_WAR"
 
 COMMAND="java -jar "$HTEMP/$PAYARA_MICRO_JAR" $PAYARA_OPTS --addjars "$HTEMP/$POSTGRESQL_JDBC_JAR" --deploy $HOLARSE_WAR --domainconfig holarse-domain.xml"
 $COMMAND
-
-
-
-
-
